---
title: "Directional Simulation"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 6, fig.height = 6
                      )
```

```{r Library, warning=FALSE}
library(spatstat.geom)
library(spatstat.random)
```

```{r Defaultsetting}
W <- owin(xrange = c(0, 10), yrange = c(0, 10))

sigma_parallel <- 0.60
sigma_perp <- 0.12
theta0 <- pi / 4
```

```{r}
n <- 100
u <- rnorm(n, mean = 0, sd = sigma_parallel)
v <- rnorm(n, mean = 0, sd = sigma_perp)

plot(u, v, asp = 1, pch = 16,
     xlab = "u", ylab = "v", main = "Before rotation")

dx <- u * cos(theta0) - v * sin(theta0)
dy <- u * sin(theta0) + v * cos(theta0)
xy <- data.frame(x = 5 + dx, y = 5 + dy)

plot(W, main = "One ellipse cluster", axes = TRUE)
points(xy$x, xy$y, pch = 16, cex = 0.6)
points(5, 5, pch = 3, col = "red", cex = 1.3)
```

```{r Parentpoints}
lambda_centers <- 0.2
X_parent <- rpoispp(lambda_centers, win = W)
xy_parent <- data.frame(x = X_parent$x, y = X_parent$y)
n_parent <- npoints(X_parent)

n_parent
plot(X_parent, main = "Cluster centres", axes = TRUE,
     pch = 3, cols = "red")
```

```{r Offspringpoints}
lambda_offspring <- 40
n_offspring <- rpois(n_parent, lambda = lambda_offspring)

n_offspring

xy <- data.frame(x = numeric(), y = numeric()) #
for (i in seq_len(n_parent)) {
  u <- rnorm(n_offspring[i], sd = sigma_parallel)
  v <- rnorm(n_offspring[i], sd = sigma_perp)
  
  xy_i <- data.frame(
    x = xy_parent$x[i] + u * cos(theta0) - v * sin(theta0),
    y = xy_parent$y[i] + u * sin(theta0) + v * cos(theta0)
  )
  xy <- rbind(xy, xy_i)
}

keep <- inside.owin(xy$x, xy$y, W) #only keep points in the window 
X <- ppp(x = xy$x[keep], y = xy$y[keep], window = W)

sum(n_offspring)
npoints(X)

plot(X, main = "Ellipse clusters", axes = TRUE, pch = 16, cex = 0.6)
plot(X, main = "Points and centres", axes = TRUE, pch = 16, cex = 0.6)
plot(X_parent, add = TRUE, pch = 3, cols = "red", cex = 1.2)
```

```{r Bufferwindow}

buffer <- 5 * max(sigma_parallel, sigma_perp)
W_sim <- owin(
  xrange = W$xrange + c(-buffer, buffer),
  yrange = W$yrange + c(-buffer, buffer)
)
```

```{r}
X_parent <- rpoispp(lambda_centers, win = W_sim)
xy_parent <- data.frame(x = X_parent$x, y = X_parent$y)
n_parent <- npoints(X_parent)
n_parent
```

```{r}
plot(W_sim, main = "Observation window and buffer", axes = TRUE, col = "grey")
plot(W, add = TRUE, col = "white", border = "red", lwd = 2)
plot(X_parent, add = TRUE, pch = 3, cols = "red", cex = 0.8)
```

```{r GP}
sigma_gp <- 0.6
rho_gp <- 3

D_gp <- as.matrix(dist(xy_parent))
Sigma_gp <- sigma_gp^2 * exp(-D_gp^2 / (2 * rho_gp^2)) #Covaariance

R_gp <- chol(Sigma_gp)

z_gp <- rnorm(n_parent)
Z_gp <- as.vector(t(R_gp) %*% z_gp)

theta_gp <- (theta0 + Z_gp) %% pi

line_length <- 0.5
dx_parent <- line_length / 2 * cos(theta_gp)
dy_parent <- line_length / 2 * sin(theta_gp)

plot(W_sim, main = "GP directions at parents", axes = TRUE)
plot(W, add = TRUE, border = "red", lwd = 2)
segments(xy_parent$x - dx_parent, xy_parent$y - dy_parent,
         xy_parent$x + dx_parent, xy_parent$y + dy_parent,
         col = "darkblue", lwd = 1.5)
plot(X_parent, add = TRUE, pch = 3, cols = "red", cex = 0.8)
```

```{r offspringGP}
n_offspring <- rpois(n_parent, lambda = lambda_offspring)
n_offspring
xy <- data.frame(x = numeric(), y = numeric())

for (i in seq_len(n_parent)) {
  u <- rnorm(n_offspring[i], sd = sigma_parallel)
  v <- rnorm(n_offspring[i], sd = sigma_perp)
  xy_i <- data.frame(
    x = xy_parent$x[i] + u * cos(theta_gp[i]) - v * sin(theta_gp[i]),
    y = xy_parent$y[i] + u * sin(theta_gp[i]) + v * cos(theta_gp[i])
  )
  xy <- rbind(xy, xy_i)
}

X <- ppp(x = xy$x, y = xy$y, window = W)
sum(n_offspring)
npoints(X)
```

```{r OffspringGPlot}
plot(X, main = "GP-directed", axes = TRUE, pch = 16, cex = 0.6)
```

```{r offspringinside}
keep <- inside.owin(xy$x, xy$y, W)
X <- ppp(x = xy$x[keep], y = xy$y[keep], window = W)
sum(n_offspring)
npoints(X)
#plot(X, main = "GP-directed Inside", axes = TRUE, pch = 16, cex = 0.6)
plot(X, axes = TRUE, pch = 16, cex = 0.6)
```

```{r}
plot(X, main = "GP-directed Inside", axes = TRUE, pch = 16, cex = 0.6)
plot(X_parent[W], add = TRUE, pch = 3, cols = "red", cex = 0.8)
```

```{r rotateGP}
rotate_gp <- function(theta_new) {
  id_parent <- rep(seq_len(n_parent), times = n_offspring)
  dx <- xy$x - xy_parent$x[id_parent]
  dy <- xy$y - xy_parent$y[id_parent]
  dtheta <- theta_new[id_parent] - theta_gp[id_parent]

  xy_new <- data.frame(
    x = xy_parent$x[id_parent] + dx * cos(dtheta) - dy * sin(dtheta),
    y = xy_parent$y[id_parent] + dx * sin(dtheta) + dy * cos(dtheta)
  )

  keep <- inside.owin(xy_new$x, xy_new$y, W)
  ppp(x = xy_new$x[keep], y = xy_new$y[keep], window = W)
}
```

```{r compareGP, fig.width=12, fig.height=6}
theta_logistic <- pi * plogis(qlogis(theta0 / pi) + Z_gp)
X_logistic <- rotate_gp(theta_logistic)

par(mfrow = c(1, 2))
plot(X, main = "mod pi", axes = TRUE, pch = 16, cex = 0.6)
plot(X_logistic, main = "Logistic", axes = TRUE, pch = 16, cex = 0.6)
par(mfrow = c(1, 1))
```

```{r , fig.width=12, fig.height=6}
z <- seq(-40, 40, length.out = 1000) 
matplot(z, cbind((theta0 + z) %% pi, pi * plogis(qlogis(theta0 / pi) + z)) * 180 / pi, pch = 16, cex = 0.3, col = c("blue", "red"), xlab = "Z(s)", ylab = "Angle (degrees)")

```

```{r AngleDensity, fig.width=12, fig.height=6}
theta0 <- 0

# Density of GP_angle
theta_mod <- (theta0 + Z_gp) %% pi
theta_logistic <- (theta0 + pi * (plogis(Z_gp) - 0.5)) %% pi


angle_density <- function(theta) {
  angle <- theta * 180 / pi
  d <- density(c(angle - 180, angle, angle + 180),
               bw = 10, from = 0, to = 180)
  d$y <- 3 * d$y
  return(d)
}

density_mod <- angle_density(theta_mod)
density_logistic <- angle_density(theta_logistic)


ylim_density <- c(0, max(density_mod$y, density_logistic$y))

par(mfrow = c(1, 1))
plot(density_mod, col = "blue", lwd = 2,
     xlim = c(0, 180), ylim = ylim_density,
     main = "Angle distributions: theta0 = 0",
     xlab = "Angle (degrees)", ylab = "Density")

lines(density_logistic, col = "red", lwd = 2)

legend("topright",
       legend = c("mod pi", "logistic"),
       col = c("blue", "red"),
       lwd = 2, bty = "n")
```

```{r GaussianVectorField, fig.width=6, fig.height=6}
# observepoint
n_field <- 500
xy_field <- data.frame(
  x = runif(n_field, W$xrange[1], W$xrange[2]),
  y = runif(n_field, W$yrange[1], W$yrange[2])
)

# 
D_field <- as.matrix(dist(xy_field))
Sigma_field <- sigma_gp^2 * exp(-D_field^2 / (2 * rho_gp^2))
Sigma_field <- Sigma_field + diag(1e-8, n_field)
R_field <- chol(Sigma_field)

# 
GP1 <- as.vector(t(R_field) %*% rnorm(n_field))
GP2 <- as.vector(t(R_field) %*% rnorm(n_field))

# (GP1,GP2)^T
vector_field <- data.frame(xy_field, GP1 = GP1, GP2 = GP2)

# plot
plot(W, main = "Gaussian vector field", axes = TRUE)
points(xy_field$x, xy_field$y, pch = 16, cex = 0.5)

arrow_scale <- 1
arrows(xy_field$x, xy_field$y,
       xy_field$x + arrow_scale * GP1,
       xy_field$y + arrow_scale * GP2,
       length = 0.06, col = "lightblue")
```
